### ISSUE TITLE
 Not Installing

### ISSUE THREAD

**Issue by Suleman-Elahi** [OthmanLan/IGViewer#1]
The extension is not installing; it throws the following error.

![image](https://user-images.githubusercontent.com/24384996/31542794-13eb6260-b031-11e7-87d4-2b573826ca9a.png)

**Comment by ohmlnz** [comment]
Hi there! 

Sorry for the delayed answer, I wasn't actively looking at this project and had to deal with a bunch of copyright issues (hence the name change). 

I have updated a few things over the past months and can't seem to replicate your issue. Would you mind letting me know if this still happens? 

Thanks!
